const rows =  [
  {
    id: '01',
    username: 'hohoaisan',
    fullname: 'Hồ Hoài Sản',
    sex: 'Nam',
    phone: '0935245367',
    email: 'hohoaisan@gmail.com',
    isDisabled: false,
    isAdmin: false,
  },
  {
    id: '02',
    username: 'hohoaisan',
    fullname: 'Hồ Hoài Sản',
    sex: 'Nam',
    phone: '0935245367',
    email: 'hohoaisan@gmail.com',
    isDisabled: false,
    isAdmin: false,
  },
  {
    id: '03',
    username: 'hohoaisan',
    fullname: 'Hồ Hoài Sản',
    sex: 'Nam',
    phone: '0935245367',
    email: 'hohoaisan@gmail.com',
    isDisabled: false,
    isAdmin: false,
  },
  {
    id: '04',
    username: 'hohoaisan',
    fullname: 'Hồ Hoài Sản',
    sex: 'Nam',
    phone: '0935245367',
    email: 'hohoaisan@gmail.com',
    isDisabled: false,
    isAdmin: true,
  },
  {
    id: '05',
    username: 'hohoaisan',
    fullname: 'Hồ Hoài Sản',
    sex: 'Nam',
    phone: '0935245367',
    email: 'hohoaisan@gmail.com',
    isDisabled: true,
    isAdmin: false,
  },
];


export default rows