import OrderDataGridRow from 'interfaces/Dashboard/OrderDataGridRow';

const rows : OrderDataGridRow[] = [
  {
    id: '1',
    status: 'completed',
    orderer: 'ho hoai san',
    receiver: 'ho hoai san',
    date: new Date().toLocaleString(),
    delivery_method: 'Thường',
    payment_method: 'Tiền mặt',
    total_items: 5,
    total: 13000,
  },
  {
    id: '2',
    status: 'pending',
    orderer: 'ho hoai san',
    receiver: 'ho hoai san',
    date: new Date().toLocaleString(),
    delivery_method: 'Thường',
    payment_method: 'Tiền mặt',
    total_items: 9,
    total: 13000,
  },
  {
    id: '3',
    status: 'unpaid',
    orderer: 'ho hoai san',
    receiver: 'ho hoai san',
    date: new Date().toLocaleString(),
    delivery_method: 'Thường',
    payment_method: 'Tiền mặt',
    total_items: 10,
    total: 13000,
  },
  {
    id: '4',
    status: 'error',
    orderer: 'ho hoai san',
    receiver: 'ho hoai san',
    date: new Date().toLocaleString(),
    delivery_method: 'Thường',
    payment_method: 'Tiền mặt',
    total_items: 10,
    total: 13000,
  },
  {
    id: '5',
    status: 'completed',
    orderer: 'ho hoai san',
    receiver: 'ho hoai san',
    date: new Date().toLocaleString(),
    delivery_method: 'Thường',
    payment_method: 'Tiền mặt',
    total_items: 10,
    total: 13000,
  },
  {
    id: '6',
    status: 'completed',
    orderer: 'ho hoai san',
    receiver: 'ho hoai san',
    date: new Date().toLocaleString(),
    delivery_method: 'Thường',
    payment_method: 'Tiền mặt',
    total_items: 10,
    total: 13000,
  },
  {
    id: '7',
    status: 'completed',
    orderer: 'ho hoai san',
    receiver: 'ho hoai san',
    date: new Date().toLocaleString(),
    delivery_method: 'Thường',
    payment_method: 'Tiền mặt',
    total_items: 10,
    total: 13000,
  },
  {
    id: '8',
    status: 'completed',
    orderer: 'ho hoai san',
    receiver: 'ho hoai san',
    date: new Date().toLocaleString(),
    delivery_method: 'Thường',
    payment_method: 'Tiền mặt',
    total_items: 10,
    total: 13000,
  },
  {
    id: '9',
    status: 'completed',
    orderer: 'ho hoai san',
    receiver: 'ho hoai san',
    date: new Date().toLocaleString(),
    delivery_method: 'Thường',
    payment_method: 'Tiền mặt',
    total_items: 10,
    total: 13000,
  },
];
export default rows
